// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYpovK19lCRkEWM2tDV8cvK6LvoThB5yg',
    appId: '1:67333358342:web:d49d54d1b4f722838d1487',
    messagingSenderId: '67333358342',
    projectId: 'harmonyevent-5b2f9',
    authDomain: 'harmonyevent-5b2f9.firebaseapp.com',
    databaseURL: 'https://harmonyevent-5b2f9-default-rtdb.firebaseio.com',
    storageBucket: 'harmonyevent-5b2f9.firebasestorage.app',
    measurementId: 'G-JJCQY2XMVD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBakJAJ7YgqkuEN3rjsWIwmLfBjTVHiRqs',
    appId: '1:67333358342:android:eb7dd669daba93518d1487',
    messagingSenderId: '67333358342',
    projectId: 'harmonyevent-5b2f9',
    databaseURL: 'https://harmonyevent-5b2f9-default-rtdb.firebaseio.com',
    storageBucket: 'harmonyevent-5b2f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSADdtL-NLTMgHNtPqKnSKTC6XhLOKrkI',
    appId: '1:67333358342:ios:fd6e891f310156978d1487',
    messagingSenderId: '67333358342',
    projectId: 'harmonyevent-5b2f9',
    databaseURL: 'https://harmonyevent-5b2f9-default-rtdb.firebaseio.com',
    storageBucket: 'harmonyevent-5b2f9.firebasestorage.app',
    iosClientId: '67333358342-e96rhbs06mjl1bmn9pfni4auh07gavvv.apps.googleusercontent.com',
    iosBundleId: 'com.example.harmonyEvent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSADdtL-NLTMgHNtPqKnSKTC6XhLOKrkI',
    appId: '1:67333358342:ios:fd6e891f310156978d1487',
    messagingSenderId: '67333358342',
    projectId: 'harmonyevent-5b2f9',
    databaseURL: 'https://harmonyevent-5b2f9-default-rtdb.firebaseio.com',
    storageBucket: 'harmonyevent-5b2f9.firebasestorage.app',
    iosClientId: '67333358342-e96rhbs06mjl1bmn9pfni4auh07gavvv.apps.googleusercontent.com',
    iosBundleId: 'com.example.harmonyEvent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYpovK19lCRkEWM2tDV8cvK6LvoThB5yg',
    appId: '1:67333358342:web:b5eb5ac188571d128d1487',
    messagingSenderId: '67333358342',
    projectId: 'harmonyevent-5b2f9',
    authDomain: 'harmonyevent-5b2f9.firebaseapp.com',
    databaseURL: 'https://harmonyevent-5b2f9-default-rtdb.firebaseio.com',
    storageBucket: 'harmonyevent-5b2f9.firebasestorage.app',
    measurementId: 'G-PBRRRD0KVG',
  );
}
